// Exercise the actual report builder with a labeled test fixture and hostile file metadata.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('script.js','utf8'),start=source.indexOf('const escapeHTML='),end=source.indexOf("$('reportButton').onclick=",start);
let blob,clicked=false,removed=false;
const analysis={risk_score:72,risk_level:'HIGH',confidence_label:'Low-confidence analysis',confidence_basis:'Unvalidated',score_kind:'Concern index',reasoning:['Test fixture'],indicators:[{name:'Test source',score:72,contribution_weight:1,description:'Fixture only'}]};
const vocal={label:'Uncertain',description:'Acoustic measurements only',features:{pitch_median_hz:180,jitter:null}};
const result={analysis_id:'test-1234',filename:'<script>alert(1)</script>.wav',timestamp:'2026-09-13T00:00:00Z',duration_seconds:4,analysis,diarization:{num_speakers:1,method:'test fixture',speakers:[{speaker_id:'Speaker 1',speaking_time_sec:4,analysis,language:{label:'Unknown'},vocal_state:vocal,suspicious_intervals:[],attribution_confidence:'uncertain'}],speaker_turns:[{speaker:'Speaker 1',start:0,end:4,overlap:false}]},language:{label:'Unknown',reason:'Unavailable',languages:[]},quality:{label:'Usable',original_sample_rate_hz:16000,candidate_speech_seconds:4,rms_dbfs:-20,clipping_fraction:0,issues:[]},vocal_state:vocal,limitations:['Test fixture, not a real finding'],recommendations:['Verify independently']};
const context={state:{result},Blob,URL:{createObjectURL:b=>{blob=b;return 'blob:test';},revokeObjectURL:()=>{}},document:{body:{append:()=>{}}},el:()=>({click:()=>{clicked=true;},remove:()=>{removed=true;}}),setTimeout:()=>{},languageNames:{},riskText:r=>`${r.risk_score}/100`,langText:l=>l.label};
vm.runInNewContext(source.slice(start,end)+'\ndownloadReport();',context);
(async()=>{const html=await blob.text();assert(clicked&&removed);assert(html.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));assert(!html.includes('<script>'));for(const label of ['test-1234','Speaker-level findings','Original recording intervals','Recording quality','Limitations','Security recommendations','Unvalidated'])assert(html.includes(label),label);assert(html.includes('@media print'));console.log('PASS: Report download trigger, complete findings, print stylesheet and HTML injection escaping.');})();
